let status = isJSON($response.body);
console.log(status);
let requestUrl = $request.url;
var obj = status
  ? JSON.parse(
      removeExtraSpaces($response.body)
        .replace(/\"isVip\":\w+/g, '"isVip":1')
        .replace(/\"nowLevelNum\":\w+/g, '"nowLevelNum":18')
        .replace(/\"experienceNum\":\w+/g, '"experienceNum":168888')
        .replace(/\"nextInitialNum\":\w+/g, '"nextInitialNum":168888')
        .replace(/\"dueTime\":\w+/g, '"dueTime":7955085722')
        .replace(/\"isObtain\":\w+/g, '"isObtain":1')
        .replace(/\"integralScore\":\w+/g, '"integralScore":999999')
        .replace(/\"lotteryNumber\":\w+/g, '"lotteryNumber":999999')
    )
  : $response.body;
if (
  /^https:\/\/medal\.iwhop\.com\/medal\/getPersonalListToShow?/.test(requestUrl)
) {
  obj.data = [
    {
      id: 1,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/gain/1_1.png",
      gainContent: "欢迎您使用Wearfit,探索之路从此开始",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/un_gain/1_1.png",
      colourlessSmallImg: "",
      typeName: "新手之路",
      medalTypeId: 1,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "喜迎贵客",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "欢迎您使用Wearfit,探索之路从此开始",
    },
    {
      id: 2,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/gain/1_2.png",
      gainContent: "守护您的健康，是Wearfit的责任",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/un_gain/1_2.png",
      colourlessSmallImg: "",
      typeName: "新手之路",
      medalTypeId: 1,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "健康天使",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "守护您的健康，是Wearfit的责任",
    },
    {
      id: 3,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/gain/1_3.png",
      gainContent: "美好旧时光的追忆，来自在应对新挑战时取得的进步",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/un_gain/1_3.png",
      colourlessSmallImg: "",
      typeName: "新手之路",
      medalTypeId: 1,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连接未来",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "美好旧时光的追忆，来自在应对新挑战时取得的进步",
    },
    {
      id: 4,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/gain/1_4.png",
      gainContent: "欲穷千里目,更上一层楼",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/un_gain/1_4.png",
      colourlessSmallImg: "",
      typeName: "新手之路",
      medalTypeId: 1,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "求知学霸",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "欲穷千里目,更上一层楼",
    },
    {
      id: 5,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/gain/1_5.png",
      gainContent: "保持使用Wearfit，迈向新征程",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/init/picture/un_gain/1_5.png",
      colourlessSmallImg: "",
      typeName: "新手之路",
      medalTypeId: 1,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "勤勉律人",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "保持使用Wearfit，迈向新征程",
    },

    {
      id: 6,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_1.png",
      gainContent: "单日步数突破2万步，突破即成功！",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_1.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "单日2万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_1.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单日步数突破2万步，突破即成功！",
    },
    {
      id: 7,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_2.png",
      gainContent: "单日步数突破3万步，突破即成功！",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_2.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "单日3万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_2.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单日步数突破3万步，突破即成功！",
    },
    {
      id: 8,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_3.png",
      gainContent: "累计运动达到1万步，不积跬步，无以至千里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_3.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计1万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_3.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到1万步，不积跬步，无以至千里",
    },
    {
      id: 9,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_4.png",
      gainContent: "累计运动达到10万步，千里之行，始于足下",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_4.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计10万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_4.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到10万步，千里之行，始于足下",
    },
    {
      id: 10,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_5.png",
      gainContent: "累计运动达到30万步，驽马十驾，功在不舍",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_5.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计30万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_5.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到30万步，驽马十驾，功在不舍",
    },
    {
      id: 11,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_6.png",
      gainContent: "累计运动达到100万步，读万卷书，行万里路",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_6.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计100万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_6.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到100万步，读万卷书，行万里路",
    },
    {
      id: 12,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_7.png",
      gainContent: "累计运动达到300万步，锲而不舍，金石可镂",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_7.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计300万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_7.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到300万步，锲而不舍，金石可镂",
    },
    {
      id: 13,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_8.png",
      gainContent: "累计运动达到500万步，立志欲坚不欲说",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_8.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计500万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_8.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到500万步，立志欲坚不欲说",
    },
    {
      id: 14,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_9.png",
      gainContent: "累计运动达到1000万步，路漫漫，修远兮",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_9.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计1000万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_9.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到1000万步，路漫漫，修远兮",
    },
    {
      id: 15,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_10.png",
      gainContent: "累计运动达到1500万步，陪伴是最长情的告白",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_10.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计1500万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_10.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到1500万步，陪伴是最长情的告白",
    },
    {
      id: 16,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_11.png",
      gainContent: "累计运动达到2000万步，积小流成江海",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_11.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计2000万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_11.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到2000万步，积小流成江海",
    },
    {
      id: 17,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_12.png",
      gainContent: "累计运动达到3000万步，积土成山，风雨兴焉",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_12.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计3000万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_12.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到3000万步，积土成山，风雨兴焉",
    },
    {
      id: 18,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_13.png",
      gainContent: "累计运动达到4000万步，九万里风鹏正举",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_13.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计4000万步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_13.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计运动达到4000万步，九万里风鹏正举",
    },
    {
      id: 19,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_14.png",
      gainContent: "连续7天，每天运动10000步，持之以恒",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_14.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续达标7天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_14.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续7天，每天运动10000步，持之以恒",
    },
    {
      id: 20,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_15.png",
      gainContent: "连续21天，每天运动10000步，持之以恒",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_15.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续达标21天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_15.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续21天，每天运动10000步，持之以恒",
    },
    {
      id: 21,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/gain/2_16.png",
      gainContent: "连续100天，每天运动10000步，持之以恒",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/step/picture/un_gain/2_16.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 2,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续达标100天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/step/3d/ios/2_16.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续100天，每天运动10000步，持之以恒",
    },
    {
      id: 43,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/gain/4_1.png",
      gainContent: "连续4周进行徒步，生命就像徒步,终将迎来最美的风景",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/un_gain/4_1.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 4,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续4周徒步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/walk/3d/ios/4_1.dae.zip",
      img3dAndroid: "",
      lessGainContent: "进入“运动”-“步行”，连续4周徒步",
    },
    {
      id: 44,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/gain/4_2.png",
      gainContent: "连续12周进行徒步，运动与生命同在，青春与快乐永存",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/un_gain/4_2.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 4,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续12周徒步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/walk/3d/ios/4_2.dae.zip",
      img3dAndroid: "",
      lessGainContent: "进入“运动”-“步行”，连续12周徒步",
    },
    {
      id: 45,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/gain/4_3.png",
      gainContent: "连续24周进行徒步，徒步健康行，雨露容诚情",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/un_gain/4_3.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 4,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续24周徒步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/walk/3d/ios/4_3.dae.zip",
      img3dAndroid: "",
      lessGainContent: "进入“运动”-“步行”，连续24周徒步",
    },
    {
      id: 46,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/gain/4_4.png",
      gainContent: "连续52周进行徒步，平凡的脚步，可以走完伟大的行程",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/walk/picture/un_gain/4_4.png",
      colourlessSmallImg: "",
      typeName: "走路",
      medalTypeId: 4,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续52周徒步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/walk/3d/ios/4_4.dae.zip",
      img3dAndroid: "",
      lessGainContent: "进入“运动”-“步行”，连续52周徒步",
    },
    {
      id: 22,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_1.png",
      gainContent: "单次跑步距离达到2公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战2公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_1.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到2公里",
    },
    {
      id: 23,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_2.png",
      gainContent: "单次跑步距离达到3公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_2.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战3公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_2.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到3公里",
    },
    {
      id: 24,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_3.png",
      gainContent: "单次跑步达到5公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_3.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战5公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_3.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步达到5公里",
    },
    {
      id: 25,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_4.png",
      gainContent: "单次跑步距离达到7公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_4.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战7公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_4.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到7公里",
    },
    {
      id: 26,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_5.png",
      gainContent: "单次跑步距离达到10公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_5.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战10公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_5.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到10公里",
    },
    {
      id: 27,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_6.png",
      gainContent: "单次跑步距离达到21.0975公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_6.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战半程马拉松",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_6.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到21.0975公里",
    },
    {
      id: 28,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_7.png",
      gainContent: "单次跑步距离达到42.195公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_7.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战全程马拉松",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_7.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到42.195公里",
    },
    {
      id: 29,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_8.png",
      gainContent: "单次跑步距离达到100公里,你就是传奇",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_8.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "挑战超级马拉松",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_8.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次跑步距离达到100公里,你就是传奇",
    },
    {
      id: 30,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_9.png",
      gainContent: "坚其志，苦其心，勤其力，必有所成",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_9.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步10公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_9.dae.zip",
      img3dAndroid: "",
      lessGainContent: "坚其志，苦其心，勤其力，必有所成",
    },
    {
      id: 31,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_10.png",
      gainContent: "累计跑步达100公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_10.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步100公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_10.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达100公里可获得",
    },
    {
      id: 32,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_11.png",
      gainContent: "累计跑步达300公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_11.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步300公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_11.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达300公里可获得",
    },
    {
      id: 33,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_12.png",
      gainContent: "累计跑步达500公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_12.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步500公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_12.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达500公里可获得",
    },
    {
      id: 34,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_13.png",
      gainContent: "累计跑步达1000公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_13.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步1000公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_13.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达1000公里可获得",
    },
    {
      id: 35,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_14.png",
      gainContent: "累计跑步达2000公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_14.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步2000公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_14.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达2000公里可获得",
    },
    {
      id: 36,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_15.png",
      gainContent: "累计跑步达2500公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_15.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步2500公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_15.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达2500公里可获得",
    },
    {
      id: 37,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_16.png",
      gainContent: "累计跑步达3500公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_16.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步3500公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_16.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达3500公里可获得",
    },
    {
      id: 38,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_17.png",
      gainContent: "累计跑步达4000公里可获得",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_17.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计跑步4000公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_17.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计跑步达4000公里可获得",
    },
    {
      id: 39,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_18.png",
      gainContent: "没有播种，何来收获，没有汗水，何来成功",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_18.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续4周跑步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_18.dae.zip",
      img3dAndroid: "",
      lessGainContent: "没有播种，何来收获，没有汗水，何来成功",
    },
    {
      id: 40,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_19.png",
      gainContent: "连续12周每周均跑步",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_19.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续12周跑步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_19.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续12周每周均跑步",
    },
    {
      id: 41,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_20.png",
      gainContent: "连续24周每周均跑步",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_20.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续24周跑步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_20.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续24周每周均跑步",
    },
    {
      id: 42,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/gain/3_21.png",
      gainContent: "连续52周每周均跑步",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/run/picture/un_gain/3_21.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续52周跑步",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/run/3d/ios/3_21.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续52周每周均跑步",
    },
    {
      id: 71,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/run/picture/gain/3_22.png",
      gainContent: "参与并完成跑量挑战",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/run/picture/un_gain/3_22.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "跑量挑战",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战",
    },
    {
      id: 72,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/all/%E9%87%91%E7%A7%8B%E4%B9%9D%E6%9C%88_zh.png",
      gainContent: "参与并完成跑量挑战",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/all/%E9%87%91%E7%A7%8B%E4%B9%9D%E6%9C%88_en.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "金秋九月 燃脂活力",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战",
    },
    {
      id: 80,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/80_0.png",
      gainContent: "参与并完成跑量挑战2024元旦线上跑",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/80_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "2024专属电子勋章",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战2024元旦线上跑",
    },
    {
      id: 81,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/81_0.png",
      gainContent: "参与并完成跑量挑战2024新春线上跑",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/81_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "2024新春线上跑勋章",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战2024新春线上跑",
    },
    {
      id: 82,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/82_0.png",
      gainContent: "参与并完成跑量挑战春节减脂大pk勋章",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/82_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "春节减脂大pk勋章",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战春节减脂大pk勋章",
    },
    {
      id: 83,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/83_0.png",
      gainContent: "参与并完成跑量挑战春天奔跑季",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/83_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "春天奔跑季",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战春天奔跑季",
    },
    {
      id: 84,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/84_0.png",
      gainContent: "参与并完成跑量挑战畅享4月 梦想起航",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/84_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "畅享4月 梦想起航",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战畅享4月 梦想起航",
    },
    {
      id: 86,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/gain/86_0.png",
      gainContent: "参与并完成跑量挑战奔向未来 六月跑酷",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/zh/ride/picture/un_gain/86_1.png",
      colourlessSmallImg: "",
      typeName: "跑步",
      medalTypeId: 3,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "奔向未来 六月跑酷",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "",
      img3dAndroid: "",
      lessGainContent: "参与并完成跑量挑战奔向未来 六月跑酷",
    },
    {
      id: 61,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_1.png",
      gainContent: "单次骑行距离达到5公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_1.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行5公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_1.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到5公里",
    },
    {
      id: 62,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_2.png",
      gainContent: "单次骑行距离达到10公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_2.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行10公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_2.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到10公里",
    },
    {
      id: 63,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_3.png",
      gainContent: "单次骑行距离达到15公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_3.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行15公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_3.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到15公里",
    },
    {
      id: 64,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_4.png",
      gainContent: "单次骑行距离达到20公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_4.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行20公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_4.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到20公里",
    },
    {
      id: 65,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_5.png",
      gainContent: "单次骑行距离达到25公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_5.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行25公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_5.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到25公里",
    },
    {
      id: 66,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_6.png",
      gainContent: "单次骑行距离达到50公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_6.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行50公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_6.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到50公里",
    },
    {
      id: 67,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_7.png",
      gainContent: "单次骑行距离达到100公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_7.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "骑行百公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_7.dae.zip",
      img3dAndroid: "",
      lessGainContent: "单次骑行距离达到100公里",
    },
    {
      id: 68,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_8.png",
      gainContent: "累计骑行达500公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_8.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计骑行500公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_8.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计骑行达500公里",
    },
    {
      id: 69,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_9.png",
      gainContent: "累计骑行达1000公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_9.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计骑行1000公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_9.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计骑行达1000公里",
    },
    {
      id: 70,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/gain/5_10.png",
      gainContent: "累计骑行达1500公里",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/ride/picture/un_gain/5_10.png",
      colourlessSmallImg: "",
      typeName: "骑行",
      medalTypeId: 5,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计骑行1500公里",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/ride/3d/ios/5_10.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计骑行达1500公里",
    },
    {
      id: 47,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_1.png",
      gainContent: "累计“完成”训练课程“100分钟”",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_1.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计健身100分钟",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_1.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计“完成”训练课程“100分钟”",
    },
    {
      id: 48,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_2.png",
      gainContent: "累计“完成”训练课程“300分钟”",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_2.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计健身300分钟",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_2.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计“完成”训练课程“300分钟”",
    },
    {
      id: 49,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_3.png",
      gainContent: "累计“完成”训练课程“1000分钟”",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_3.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计健身1000分钟",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_3.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计“完成”训练课程“1000分钟”",
    },
    {
      id: 50,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_4.png",
      gainContent: "累计“完成”训练课程“2000分钟”",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_4.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计健身2000分钟",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_4.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计“完成”训练课程“2000分钟”",
    },
    {
      id: 51,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_5.png",
      gainContent: "累计“完成”训练课程“5000分钟”",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_5.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "累计健身5000分钟",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_5.dae.zip",
      img3dAndroid: "",
      lessGainContent: "累计“完成”训练课程“5000分钟”",
    },
    {
      id: 52,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_6.png",
      gainContent: "连续健身2天，有志者事竟成",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_6.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身2天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_6.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身2天，有志者事竟成",
    },
    {
      id: 53,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_7.png",
      gainContent: "连续健身3天，贵在坚持，难在坚持，成在坚持",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_7.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身3天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_7.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身3天，贵在坚持，难在坚持，成在坚持",
    },
    {
      id: 54,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_8.png",
      gainContent: "连续健身5天，把汗水变成珍珠，把梦想变成现实",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_8.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身5天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_8.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身5天，把汗水变成珍珠，把梦想变成现实",
    },
    {
      id: 55,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_9.png",
      gainContent: "连续健身7天，天行健，君子以自强不息",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_9.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身7天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_9.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身7天，天行健，君子以自强不息",
    },
    {
      id: 56,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_10.png",
      gainContent: "连续健身10天，锲而不舍，金石可镂",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_10.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身10天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_10.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身10天，锲而不舍，金石可镂",
    },
    {
      id: 57,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_11.png",
      gainContent: "连续健身14天山顶对半山腰的人来说并不遥远",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_11.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身14天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_11.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身14天山顶对半山腰的人来说并不遥远",
    },
    {
      id: 58,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_12.png",
      gainContent: "连续健身21天，毅力是永久的享受",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_12.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身21天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_12.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身21天，毅力是永久的享受",
    },
    {
      id: 59,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_13.png",
      gainContent: "连续健身50天，成功最终属于坚持不懈的人",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_13.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身50天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_13.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身50天，成功最终属于坚持不懈的人",
    },
    {
      id: 60,
      colourBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/gain/6_14.png",
      gainContent: "连续健身100天，玩强的毅力可以征服世界上任何一座高峰",
      colourlessBigImg:
        "https://oss.iwhop.cn/cdn/medal/fc/keep/picture/un_gain/6_14.png",
      colourlessSmallImg: "",
      typeName: "健身",
      medalTypeId: 6,
      descInfo: "",
      colourSmallImg: "",
      isObtain: 1,
      medalName: "连续健身100天",
      virtualNum: 0,
      realNum: 0,
      getTime: 0,
      img3dIos: "https://oss.iwhop.cn/cdn/medal/fc/keep/3d/ios/6_14.dae.zip",
      img3dAndroid: "",
      lessGainContent: "连续健身100天，玩强的毅力可以征服世界上任何一座高峰",
    },
  ];
}
console.log(JSON.stringify(obj));
$done({ body: status ? JSON.stringify(obj) : obj });

function isJSON(str) {
  try {
    JSON.parse(str);
  } catch (e) {
    return false;
  }
  return true;
}

function removeExtraSpaces(jsonString) {
  var jsonObj = JSON.parse(jsonString);
  return JSON.stringify(jsonObj, function (key, value) {
    if (typeof value === "string") {
      return value.trim();
    }
    return value;
  });
}
